services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      args:
        TARGET: prod
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_HOST: db
        POSTGRES_PORT: "5432"
        POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    command: >
        sh -c '
        export DB_PASSWORD="$$(cat /run/secrets/db_password)";
        export DATABASE_URL="postgresql://${POSTGRES_USER}:$${DB_PASSWORD}@db:5432/${POSTGRES_DB}";
        exec uvicorn main:app --host 0.0.0.0 --port 8000
        '
    secrets:
       - db_password
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8000"

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/', timeout=2)"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  pgdata:

secrets:
  db_password:
    file: ./secrets/db_password.txt
